modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="survivalmod"
version="1.0.0"
displayName="SurvivalMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Mateis"

[[dependencies.survivalmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




